// src/components/AgentCard.tsx
import { useState } from 'react';
import type { CatalogAgent } from '../types/adl';
import {
  deriveDisplayName,
  deriveDocs,
  deriveImage,
  deriveProvider,
  deriveRepository,
  deriveTags,
} from '../utils/adl';

interface AgentCardProps {
  agent: CatalogAgent;
}

export function AgentCard({ agent }: AgentCardProps) {
  const [copiedImage, setCopiedImage] = useState(false);
  const [copiedCommand, setCopiedCommand] = useState(false);

  const name = agent.metadata.name;
  const displayName = deriveDisplayName(agent);
  const version = agent.metadata.version;
  const description = agent.metadata.description;
  const tags = deriveTags(agent);
  const image = deriveImage(agent);
  const repository = deriveRepository(agent);
  const docs = deriveDocs(agent);
  const provider = deriveProvider(agent);
  const model = agent.spec?.agent?.model || '';
  const capabilities = agent.spec?.capabilities;
  const toolsCount = agent.spec?.tools?.length ?? 0;
  const skillsCount = agent.spec?.skills?.length ?? 0;

  const copyImageToClipboard = async () => {
    if (!image) return;
    try {
      await navigator.clipboard.writeText(`${image.repository}:${image.tag}`);
      setCopiedImage(true);
      setTimeout(() => setCopiedImage(false), 2000);
    } catch (err) {
      console.error('Failed to copy to clipboard:', err);
    }
  };

  const copyCommandToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(`infer agents add ${name}`);
      setCopiedCommand(true);
      setTimeout(() => setCopiedCommand(false), 2000);
    } catch (err) {
      console.error('Failed to copy to clipboard:', err);
    }
  };

  return (
    <div className="group relative bg-slate-800/40 backdrop-blur-xl rounded-3xl shadow-2xl hover:shadow-blue-500/10 transition-all duration-500 transform hover:-translate-y-2 overflow-hidden border border-slate-700/50 hover:border-blue-500/50 hover:bg-slate-800/60 flex flex-col h-full">
      <div className="relative p-6 flex flex-col flex-1">
        <div className="absolute inset-0 bg-gradient-to-br from-blue-500/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500 rounded-3xl"></div>

        <div className="relative flex items-start justify-between mb-6 gap-3">
          <div className="flex-1 min-w-0">
            <h3 className="text-2xl font-bold text-white mb-2 group-hover:text-blue-200 transition-colors duration-300 truncate">
              {displayName}
            </h3>
            <p className="text-slate-400 text-sm font-medium truncate">
              v{version} • <span className="text-blue-400">{name}</span>
            </p>
          </div>
          {provider && (
            <span className="px-4 py-2 bg-gradient-to-r from-blue-500 to-cyan-500 text-white text-xs font-bold rounded-full shadow-lg shadow-blue-500/25 whitespace-nowrap">
              {provider}
            </span>
          )}
        </div>

        <p className="relative text-slate-300 mb-6 line-clamp-3 leading-relaxed">{description}</p>

        {capabilities && (
          <div className="relative flex flex-wrap gap-2 mb-6">
            {capabilities.streaming && (
              <span className="px-3 py-1 bg-emerald-500/10 text-emerald-300 text-xs font-semibold rounded-full border border-emerald-500/30">
                Streaming
              </span>
            )}
            {capabilities.pushNotifications && (
              <span className="px-3 py-1 bg-purple-500/10 text-purple-300 text-xs font-semibold rounded-full border border-purple-500/30">
                Push
              </span>
            )}
            {capabilities.stateTransitionHistory && (
              <span className="px-3 py-1 bg-amber-500/10 text-amber-300 text-xs font-semibold rounded-full border border-amber-500/30">
                State History
              </span>
            )}
            <span className="px-3 py-1 bg-slate-700/50 text-slate-300 text-xs font-semibold rounded-full border border-slate-600/30">
              {toolsCount} {toolsCount === 1 ? 'tool' : 'tools'}
            </span>
            {skillsCount > 0 && (
              <span className="px-3 py-1 bg-slate-700/50 text-slate-300 text-xs font-semibold rounded-full border border-slate-600/30">
                {skillsCount} {skillsCount === 1 ? 'skill' : 'skills'}
              </span>
            )}
          </div>
        )}

        {tags.length > 0 && (
          <div className="relative flex flex-wrap gap-2 mb-6">
            {tags.slice(0, 8).map((tag) => (
              <span
                key={tag}
                className="px-2 py-1 bg-slate-900/50 text-slate-400 text-xs rounded-md border border-slate-700/30"
              >
                #{tag}
              </span>
            ))}
            {tags.length > 8 && (
              <span className="px-2 py-1 text-slate-500 text-xs">+{tags.length - 8} more</span>
            )}
          </div>
        )}

        <div className="flex-1"></div>

        <div className="relative border-t border-slate-700/50 pt-6">
          {model && (
            <div className="grid grid-cols-1 gap-4 text-sm mb-4">
              <div>
                <span className="text-slate-400 text-xs uppercase tracking-wider">Model</span>
                <p className="font-mono text-white truncate mt-1">{model}</p>
              </div>
            </div>
          )}

          <div className="mb-4">
            <span className="text-slate-400 text-xs uppercase tracking-wider mb-2 block">
              Add to CLI
            </span>
            <div className="flex items-center gap-1 p-2 bg-slate-900/50 rounded-xl border border-slate-700/30">
              <code className="flex-1 text-xs text-green-300 font-mono truncate">
                infer agents add {name}
              </code>
              <button
                onClick={copyCommandToClipboard}
                className={`flex items-center justify-center w-6 h-6 rounded-lg transition-all duration-200 ${
                  copiedCommand
                    ? 'bg-green-500/20 text-green-400'
                    : 'bg-slate-700/50 hover:bg-slate-600/50 text-slate-300 hover:text-white'
                }`}
                title="Copy CLI command"
              >
                {copiedCommand ? (
                  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M5 13l4 4L19 7"
                    />
                  </svg>
                ) : (
                  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"
                    />
                  </svg>
                )}
              </button>
            </div>
          </div>

          {image && (
            <div className="mb-6">
              <span className="text-slate-400 text-xs uppercase tracking-wider mb-2 block">
                OCI Image
              </span>
              <div className="flex items-center gap-1 p-2 bg-slate-900/50 rounded-xl border border-slate-700/30">
                <code className="flex-1 text-xs text-blue-300 font-mono truncate">
                  {image.repository}:{image.tag}
                </code>
                <button
                  onClick={copyImageToClipboard}
                  className={`flex items-center justify-center w-6 h-6 rounded-lg transition-all duration-200 ${
                    copiedImage
                      ? 'bg-green-500/20 text-green-400'
                      : 'bg-slate-700/50 hover:bg-slate-600/50 text-slate-300 hover:text-white'
                  }`}
                  title="Copy OCI image URL"
                >
                  {copiedImage ? (
                    <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M5 13l4 4L19 7"
                      />
                    </svg>
                  ) : (
                    <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"
                      />
                    </svg>
                  )}
                </button>
              </div>
            </div>
          )}

          <div className="relative flex gap-3 pt-6 border-t border-slate-700/50">
            {repository && (
              <a
                href={repository}
                target="_blank"
                rel="noopener noreferrer"
                className="flex-1 text-center px-4 py-3 bg-slate-700/50 hover:bg-slate-600/50 text-white rounded-xl transition-all duration-300 text-sm font-semibold backdrop-blur-sm border border-slate-600/30 hover:border-slate-500/50 group-hover:shadow-lg"
              >
                <div className="flex items-center justify-center gap-2">
                  <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 24 24">
                    <path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z" />
                  </svg>
                  Repository
                </div>
              </a>
            )}
            {docs && (
              <a
                href={docs}
                target="_blank"
                rel="noopener noreferrer"
                className="flex-1 text-center px-4 py-3 bg-gradient-to-r from-blue-600 to-cyan-600 hover:from-blue-500 hover:to-cyan-500 text-white rounded-xl transition-all duration-300 text-sm font-semibold shadow-lg shadow-blue-500/25 hover:shadow-blue-500/40 hover:shadow-xl"
              >
                <div className="flex items-center justify-center gap-2">
                  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"
                    />
                  </svg>
                  Documentation
                </div>
              </a>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

// docs/.vitepress/components/AgentCard.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import type { CatalogAgent } from "../lib/types";
import {
  deriveDisplayName,
  deriveDocs,
  deriveImage,
  deriveLanguage,
  deriveProvider,
  deriveRepository,
  deriveTags,
} from "../lib/adl";

const props = defineProps<{ agent: CatalogAgent }>();

const copiedCommand = ref(false);
const copiedImage = ref(false);
type Panel = "tools" | "skills" | null;
const openPanel = ref<Panel>(null);

const displayName = computed(() => deriveDisplayName(props.agent));
const tags = computed(() => deriveTags(props.agent));
const image = computed(() => deriveImage(props.agent));
const repository = computed(() => deriveRepository(props.agent));
const docs = computed(() => deriveDocs(props.agent));
const provider = computed(() => deriveProvider(props.agent));
const model = computed(() => props.agent.spec?.agent?.model || "");
const language = computed(() => deriveLanguage(props.agent));
const capabilities = computed(() => props.agent.spec?.capabilities);
const tools = computed(() => props.agent.spec?.tools ?? []);
const skills = computed(() => props.agent.spec?.skills ?? []);
const installCommand = computed(
  () => `infer agents add ${props.agent.metadata.name}`,
);

const badgeText = computed(
  () => provider.value || model.value || language.value || "",
);

function togglePanel(p: Exclude<Panel, null>) {
  openPanel.value = openPanel.value === p ? null : p;
}

async function copy(text: string, flag: { value: boolean }) {
  try {
    await navigator.clipboard.writeText(text);
    flag.value = true;
    setTimeout(() => (flag.value = false), 2000);
  } catch (err) {
    console.error("Failed to copy to clipboard:", err);
  }
}
</script>

<template>
  <article class="reg-card">
    <header class="reg-card__head">
      <div style="min-width: 0">
        <h3 class="reg-card__title">{{ displayName }}</h3>
        <div class="reg-card__sub">
          v{{ agent.metadata.version }} ·
          <span class="reg-card__sub-accent">{{ agent.metadata.name }}</span>
        </div>
      </div>
      <span v-if="badgeText" class="reg-card__badge">{{ badgeText }}</span>
    </header>

    <p class="reg-card__desc">{{ agent.metadata.description }}</p>

    <div class="reg-card__pills">
      <span v-if="capabilities?.streaming" class="reg-pill reg-pill--accent"
        >Streaming</span
      >
      <span
        v-if="capabilities?.pushNotifications"
        class="reg-pill reg-pill--accent"
        >Push</span
      >
      <span
        v-if="capabilities?.stateTransitionHistory"
        class="reg-pill reg-pill--accent"
      >
        State History
      </span>
      <button
        v-if="tools.length > 0"
        type="button"
        class="reg-pill reg-pill--button"
        :class="{ 'is-open': openPanel === 'tools' }"
        :aria-expanded="openPanel === 'tools'"
        @click="togglePanel('tools')"
      >
        <span class="reg-pill__chev" aria-hidden="true">›</span>
        {{ tools.length }} {{ tools.length === 1 ? "tool" : "tools" }}
      </button>
      <button
        v-if="skills.length > 0"
        type="button"
        class="reg-pill reg-pill--button"
        :class="{ 'is-open': openPanel === 'skills' }"
        :aria-expanded="openPanel === 'skills'"
        @click="togglePanel('skills')"
      >
        <span class="reg-pill__chev" aria-hidden="true">›</span>
        {{ skills.length }} {{ skills.length === 1 ? "skill" : "skills" }}
      </button>
    </div>

    <div v-if="openPanel === 'tools'" class="reg-card__panel">
      <ul class="reg-card__panel-list">
        <li v-for="tool in tools" :key="tool.id" class="reg-card__panel-item">
          <div class="reg-card__panel-head">
            <span class="reg-card__panel-name">{{ tool.name || tool.id }}</span>
            <span
              v-if="tool.name && tool.name !== tool.id"
              class="reg-card__panel-id"
            >
              {{ tool.id }}
            </span>
          </div>
          <p v-if="tool.description" class="reg-card__panel-desc">
            {{ tool.description }}
          </p>
          <div v-if="tool.tags && tool.tags.length > 0" class="reg-card__pills">
            <span
              v-for="tag in tool.tags"
              :key="tag"
              class="reg-pill reg-pill--tag"
            >
              #{{ tag }}
            </span>
          </div>
        </li>
      </ul>
    </div>

    <div v-if="openPanel === 'skills'" class="reg-card__panel">
      <ul class="reg-card__panel-list">
        <li
          v-for="skill in skills"
          :key="skill.id"
          class="reg-card__panel-item"
        >
          <div class="reg-card__panel-head">
            <span class="reg-card__panel-name">{{
              skill.name || skill.id
            }}</span>
            <span v-if="skill.license" class="reg-card__panel-license">
              {{ skill.license }}
            </span>
          </div>
          <p v-if="skill.description" class="reg-card__panel-desc">
            {{ skill.description }}
          </p>
          <div
            v-if="skill.tags && skill.tags.length > 0"
            class="reg-card__pills"
          >
            <span
              v-for="tag in skill.tags"
              :key="tag"
              class="reg-pill reg-pill--tag"
            >
              #{{ tag }}
            </span>
          </div>
          <a
            v-if="skill.source"
            class="reg-card__panel-link"
            :href="skill.source"
            target="_blank"
            rel="noopener noreferrer"
          >
            View source ↗
          </a>
        </li>
      </ul>
    </div>

    <div v-if="tags.length > 0" class="reg-card__pills">
      <span
        v-for="tag in tags.slice(0, 8)"
        :key="tag"
        class="reg-pill reg-pill--tag"
      >
        #{{ tag }}
      </span>
      <span v-if="tags.length > 8" class="reg-pill reg-pill--tag">
        +{{ tags.length - 8 }} more
      </span>
    </div>

    <div class="reg-card__spacer" />

    <div v-if="model" class="reg-card__section">
      <span class="reg-card__label">Model</span>
      <span class="reg-card__model">{{ model }}</span>
    </div>

    <div class="reg-card__section">
      <span class="reg-card__label">Add to CLI</span>
      <div class="reg-card__code-row">
        <code>{{ installCommand }}</code>
        <button
          class="reg-card__copy"
          :class="{ 'is-copied': copiedCommand }"
          :title="copiedCommand ? 'Copied' : 'Copy CLI command'"
          @click="copy(installCommand, copiedCommand)"
        >
          <svg
            v-if="copiedCommand"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M5 13l4 4L19 7"
            />
          </svg>
          <svg v-else fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"
            />
          </svg>
        </button>
      </div>
    </div>

    <div v-if="image" class="reg-card__section">
      <span class="reg-card__label">OCI Image</span>
      <div class="reg-card__code-row">
        <code>{{ image.repository }}:{{ image.tag }}</code>
        <button
          class="reg-card__copy"
          :class="{ 'is-copied': copiedImage }"
          :title="copiedImage ? 'Copied' : 'Copy OCI image URL'"
          @click="copy(`${image.repository}:${image.tag}`, copiedImage)"
        >
          <svg
            v-if="copiedImage"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M5 13l4 4L19 7"
            />
          </svg>
          <svg v-else fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z"
            />
          </svg>
        </button>
      </div>
    </div>

    <div v-if="repository || docs" class="reg-card__actions">
      <a
        v-if="repository"
        class="reg-card__action reg-card__action--ghost"
        :href="repository"
        target="_blank"
        rel="noopener noreferrer"
      >
        <svg fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
          <path
            d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"
          />
        </svg>
        Repository
      </a>
      <a
        v-if="docs"
        class="reg-card__action reg-card__action--primary"
        :href="docs"
        target="_blank"
        rel="noopener noreferrer"
      >
        <svg
          fill="none"
          stroke="currentColor"
          viewBox="0 0 24 24"
          aria-hidden="true"
        >
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"
          />
        </svg>
        Documentation
      </a>
    </div>
  </article>
</template>
